version: "3.8"

services:
  blitz_compilation:
    build:
      context: .
      args:
        - COMPILE_ALL=${COMPILE_ALL}
        - FOR_X=${FOR_X}
    privileged: true
    environment:
      BLITZ_USER: ${BLITZ_USER:-ubuntu}
      BLITZ_PASSWORD: ${BLITZ_PASSWORD:-ubuntu}
      BLITZ_UID: ${BLITZ_UID:-1000}
      BLITZ_GID: ${BLITZ_GID:-1000}
    stdin_open: true
    volumes:
      - .:/host
    tty: true
    ports:
      - "6756:6756"
